# Generated by Django 4.0.4 on 2023-04-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeView', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='child',
            new_name='parent',
        ),
    ]
